name: Test Dead Link

on:
  push:
    branches: [ main ]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check links
        uses: restqa/404-links@3.1.4
        with:
          ignore:
            urls:
              - https://open.sap.com/*
              - https://www.sap.com/*
              - https://www.linkedin.com/in/*